---
- name: Demo debug features
  hosts: all
  tasks:

    - name: Print data 
      ansible.builtin.debug:
        var: ansible_facts 

    - name: Initiate error 
      ansible.builtin.command:
        cmd: "echo {{ undefined_var }}"

    - name: Print data 
      ansible.builtin.debug:
        var: ansible_facts 

    - name: Initiate error 
      ansible.builtin.command:
        cmd: "echo {{ undefined_var_2 }}"

    - name: Print data 
      ansible.builtin.debug:
        var: ansible_facts 