---
- name: Demo debug features
  hosts: all
  tasks:

    - name: Print data 
      ansible.builtin.debug:
        var: ansible_facts 

    - name: Initiate error 
      ansible.builtin.command:
        cmd: "echo {{ undefined_var }}"
      ignore_errors: true 

    - name: Print data 
      ansible.builtin.debug:
        var: ansible_facts 

    - name: Initiate error 
      ansible.builtin.command:
        cmd: "echo {{ undefined_var_2 }}"
      ignore_errors: true

    - name: Print data 
      ansible.builtin.debug:
        var: ansible_facts 